--- Browse databases, run queries, and edit results without leaving Neovim.
---
--- The plugin has two sides: Lua code draws the windows you see (the drawer
--- on the side, scratchpads where you write queries, the grid that shows
--- results), while a separate Rust engine talks to your databases and holds
--- the results. That split keeps the editor responsive while queries run.
--- See README.md for installation, then follow |sqmeow-quickstart| below.
--- Use |sqmeow-commands| for commands and |sqmeow-api| for Lua.
---@tag sqmeow.nvim
---@toc_entry Introduction

--- Contents ~
---@toc

--- Quick start ~
---
--- 1. Run `:Sqmeow` to open the drawer and result window.
--- 2. Press `A` to add a connection, or create |sqmeow-project| configuration.
--- 3. Press <CR> on a connection to open it; `u` selects it for queries.
--- 4. Press `a` to create a scratchpad, such as `example.sql`.
--- 5. Write `SELECT 1;`, then press <CR> to run the statement under the cursor.
---
--- A few words so the steps make sense. The drawer is the sidebar that lists
--- your connections, tables, scratchpads, and history. A scratchpad is an
--- ordinary SQL file where you write and run queries. The result window shows
--- what came back in a grid you can page, filter, and edit.
---
--- Visual <CR> runs the selected lines and <leader>E runs the whole buffer.
--- In the result, `L`/`H` turn pages and `K` shows the full row. Press `?` in
--- any window to see its mappings. Closing a window only hides it; your
--- connection stays open until `:Sqmeow disconnect`.
---@tag sqmeow-quickstart
---@toc_entry Quick start

--- Commands ~
---
--- `:Sqmeow` opens the drawer and result window. Every subcommand completes
--- with <Tab>, so you can explore by typing `:Sqmeow ` and pressing <Tab>.
--- Brackets below mark arguments you may leave out.
---
--- Connections:
---   :Sqmeow add                  Add a connection through an input form.
---   :Sqmeow save [name url]      Save a connection URL, or prompt for the current one.
---   :Sqmeow edit [name]          Edit a saved connection; without a name, pick from a list.
---   :Sqmeow remove {name}        Delete a saved entry and close its connection.
---   :Sqmeow use [name]           Make an open connection the active one, or pick from a list.
---   :Sqmeow bind [name|none]     Pin this buffer to a connection, clear the pin, or show it.
---   :Sqmeow disconnect          Close the current connection and its child databases.
---
--- Queries and results:
---   :Sqmeow scratch [name]       Create a named scratchpad, or prompt for a name.
---   :Sqmeow execute [sql]        Run the given SQL, or the whole buffer when omitted.
---   :[range]Sqmeow execute      Run an inclusive line range, e.g. `:2,5Sqmeow execute`.
---   :Sqmeow statement           Run the single statement under the cursor.
---   :Sqmeow cancel              Ask a running query or edit apply to stop.
---   :Sqmeow next / prev         Turn the displayed result page.
---   :Sqmeow review              Review staged edits before applying them.
---   :Sqmeow export [format] [path|clipboard]
---                               Export as csv, json, or sql; prompts when no destination is given.
---   :Sqmeow log [clear]         Reopen a logged result, or wipe the saved history.
---
--- Windows and engine:
---   :Sqmeow toggle              Show both windows, or hide them when visible.
---   :Sqmeow drawer              Open the drawer.
---   :Sqmeow open / close        Show or hide the result window.
---   :Sqmeow float               Move the result between a split and a floating window.
---   :Sqmeow install [method] [version]
---                               Install the engine by download or cargo build.
---   :Sqmeow start / stop / restart
---                               Manage the background engine process.
---   :Sqmeow messages            Show recent engine log messages.
---   :Sqmeow health              Run :checkhealth sqmeow.
---
--- Project connections live in their TOML file, so edit them there instead of
--- with these commands. `remove` still closes their open connections; it just
--- cannot delete the definition itself. Stopping or restarting the engine
--- closes connections and drops in-memory results, but anything archived to
--- disk stays available through |sqmeow-history|.
---@tag sqmeow-commands
---@toc_entry Commands

--- Making a connection ~
---
--- `:Sqmeow add` (or `A` in the drawer) opens a form with named fields such
--- as host, port, and user. Prefer pasting a full URL instead? Choose the
--- `Connection string` option and paste it there, including any driver
--- options or credential templates.
--- Press `e` on a saved entry to change it. New URL, read-only, and SSH
--- settings apply the next time you connect; renaming only relabels the
--- already-open connection.
---
--- You may leave the database field empty. Where the server allows it, the
--- connection then lists its databases so you can browse and open them.
--- PostgreSQL databases open as child connections named `connection/database`.
--- `:Sqmeow use` marks one of the already-open connections as active; it never
--- opens a saved entry by itself. From Lua, open saved entries with
--- |sqmeow.api.connection.connect_named()|.
---
--- Common URL forms: >text
---   postgres://user:password@localhost:5432/app
---   mysql://user:password@localhost:3306/app
---   mssql://sa:password@localhost:1433/master
---   sqlite:/absolute/path/app.db
---   duckdb:/absolute/path/app.duckdb
---   redis://localhost:6379/0
---   mongodb://localhost:27017/app
---   scylla://localhost:9042/keyspace
---   surrealdb://root:password@localhost:8000/namespace/database
---   clickhouse://localhost:8123/default
---   oracle://user:password@localhost:1521/FREEPDB1
--- <
--- In URLs, percent-encode reserved characters in credentials, writing `@`
--- as `%40` for example. The input form and the project field loader do this
--- encoding for you, so it only matters for hand-written URLs.
--- For Redis Cluster or Sentinel, connect through a URL with `redis+cluster://`
--- or `redis+sentinel://`; project TOML has no separate fields for these modes.
---@tag sqmeow-connecting
---@toc_entry Making a connection

--- Connection sources ~
---
--- Connections come from two places, and both are always loaded, in this
--- order. Project definitions are for sharing with your team through git;
--- saved connections are personal, kept in your Neovim data directory.
--- When two entries share a name, the conflict is reported and the project
--- entry wins. When one source fails, its error is reported but the other
--- source's entries still show up. Listing definitions never touches the
--- database; nothing connects until you open one.
---
---   project   Nearest .sqmeow/connections.toml; see |sqmeow-project|.
---   file      JSON array in core.path/connections.json.
---
--- Saved connections use this format: >json
---   [
---     {
---       "name": "dev",
---       "url": "postgres://app@localhost/dev",
---       "read_only": true,
---       "ssh": "user@bastion"
---     }
---   ]
--- <
--- Only `name` and `url` are required. `read_only` defaults to false, and
--- leaving out `ssh` means a direct connection. Set `core.path` to move saved
--- connections together with the plugin's other files.
---
--- `:Sqmeow add` and `:Sqmeow save` write to `core.path/connections.json` and
--- never touch project TOML. Credential templates such as
--- `{{ env "PGPASSWORD" }}` work in saved URLs too.
---@tag sqmeow-sources
---@toc_entry Connection sources

--- Project connections ~
---
--- Project connections live in a `.sqmeow/connections.toml` file inside your
--- project, so the whole team shares the same setup through git. Passwords
--- stay out of the file through credential templates (see the `.env`
--- paragraph below).
---
--- Lookup starts at the current window's directory (`:pwd`) and walks upward
--- until it finds the file. Only the nearest file counts; parent configs are
--- never merged. Lookup follows `:cd`, `:lcd`, and `:tcd` rather than the
--- current buffer's location. The file is reread every time sources load: >toml
---   [dev_db]
---   type = "postgres"
---   host = "localhost"
---   port = 5432
---   database = "my_app_dev"
---   user = "dev_user"
---   password = '{{ env "PGPASSWORD" }}'
---   read_only = true
---
---   [local_sqlite]
---   type = "sqlite"
---   path = ".sqmeow/test.db"
--- <
--- Each `[section]` names one connection. Quote names that contain dots, as in
--- `["app.dev"]`. Describe each connection with either a complete `url` or a
--- `type` plus dialect fields, never both mixed in one entry. Known types:
---   postgres, mysql, mssql, sqlite, duckdb, redis, mongodb, scylla,
---   surrealdb, clickhouse, oracle.
---
--- URL entries need no `type`, and `read_only` with `ssh` work there too: >toml
---   [dev_url]
---   url = "{{ env 'DATABASE_URL' }}"
---   read_only = true
--- <
--- Secrets stay out of the TOML through a `.env` file placed next to `.sqmeow/`,
--- which the engine reads when connecting. Variables from your real
--- environment win over the file, and a missing file is simply ignored.
--- These values are scoped to that one connection: they never leak into the
--- Neovim process and never come back to the editor. Single, double, and
--- backtick quotes all work inside `env`. After changing `.env`, reconnect so
--- the engine picks it up, and keep the file out of version control. Remember
--- that `.env` is plain text, not an encrypted vault.
---
--- Fields available per dialect:
---   host, database, user, password   Strings; host defaults to localhost.
---   port                             A number from 1 to 65535; leaving it out uses the driver default.
---   read_only                        True blocks writes; defaults to false.
---   ssh                              Host to tunnel through, e.g. `user@bastion`.
---   options                          Extra URL query string, where the dialect supports it.
---   tls                              Secure transport for Redis, SurrealDB, ClickHouse, Oracle.
---   srv                              MongoDB SRV mode; leave out `port` when true.
---   namespace                        SurrealDB namespace.
---   path                             Database file; required for SQLite and DuckDB.
---
--- A relative `path` resolves from the directory that contains `.sqmeow`, so it
--- works no matter which subdirectory Neovim is in. `path = ":memory:"` gives
--- you an empty database that disappears when the connection closes; use a
--- file path whenever the data should survive.
---
--- A missing file is fine and simply ignored. But invalid TOML, unknown
--- fields, or wrong value types reject the whole file, and the error names
--- its path, while other sources keep loading normally. Note that reading the
--- TOML may start the engine, so keep the engine build matching. Project
--- files accept `env` and `file` templates but not `exec`. When an open
--- connection shares its name with a project entry yet differs in URL,
--- read-only, or SSH settings, disconnect it first, then connect the project
--- definition. Edit these connections directly in the TOML file.
---@tag sqmeow-project
---@toc_entry Project connections

--- Credentials and SSH ~
---
--- Connection URLs may contain templates, which the engine fills in when
--- connecting, so secrets never sit in plain text: >text
---   {{ env "PGPASSWORD" }}          Read an environment variable.
---   {{ file "~/.secrets/database" }} Read a UTF-8 file; trailing whitespace is trimmed.
---   {{ exec "pass show db/dev" }}    Run a shell command; trailing whitespace is trimmed.
--- <
--- Shell commands time out after 30 seconds. Templates expand exactly once,
--- and values are inserted literally without URL-encoding, so percent-encode
--- them yourself when needed. They read the engine process's environment, so
--- restart the engine after changing environment variables inside Neovim.
--- Expanded URLs are never sent back to the editor. `redact_urls` hides
--- passwords in displayed URLs, but it does not encrypt saved definitions.
---
--- When a database is reachable only through another machine, set
--- `ssh = "user@bastion"` or a Host alias from your `~/.ssh/config`, and the
--- connection is tunneled through it using your existing SSH config, keys,
--- and agent. A custom SSH port goes after a colon, as in `user@bastion:2222`.
--- The database host is resolved from the SSH server's point of view, so
--- `localhost` there means the remote machine itself.
---@tag sqmeow-credentials
---@toc_entry Credentials and SSH

--- Which database a query runs on ~
---
--- With several databases open, each query needs to know which one to run
--- on. `:Sqmeow use` marks one open connection as active, and any scratchpad
--- without its own pin runs against it. To pin one buffer to a specific
--- database regardless of the active one, run `:Sqmeow bind dev`; this stores
--- the name in `b:sqmeow_connection`. Plain `:Sqmeow bind` shows the pin and
--- `:Sqmeow bind none` removes it.
---
--- A pinned buffer insists on its named connection being open and reports an
--- error otherwise; it never quietly runs somewhere else. An unpinned buffer
--- follows the active connection and fails with a reminder when none is set.
--- From Lua, resolve the same logic with |sqmeow.api.connection.target()|.
---@tag sqmeow-active
---@toc_entry Which database a query runs on

--- Query and result workflow ~
---
--- Three ways to run code, from narrowest to widest. `:Sqmeow statement`
--- runs the single statement under the cursor, `:Sqmeow execute` runs the
--- whole buffer, and `:'<,'>Sqmeow execute` runs only the selected lines. The
--- matching scratchpad mappings are listed under |sqmeow-keymaps|. When one
--- script returns several results, `]r` and `[r` flip between them.
---
--- Three limits shape every run. `query.max_rows` caps how many rows are kept
--- per result, with 0 meaning keep everything; results that hit the cap are
--- marked truncated. `ui.result.page_size` sets how many of those kept rows
--- one page shows; raising it never fetches rows past the cap. And
--- `query.timeout_ms` cancels work that runs too long, with 0 turning the
--- deadline off. You can always stop things by hand with <C-c> or
--- `:Sqmeow cancel`.
--- Stopping is a request, not a guarantee: a write already sent to
--- MySQL/PostgreSQL, or work already sent to Oracle/SurrealDB, runs to its
--- real outcome, so cancellation may report back late. Scylla/Cassandra and
--- standalone MongoDB stop between writes and tell you which ones finished.
--- When in doubt, check the data before retrying. Oracle atomic edits refuse
--- DDL, transaction controls, and PL/SQL blocks.
---
--- Parameterized scratchpads ~
--- Instead of editing values into the query text, write named placeholders
--- like `:user_id` and answer a prompt each time you run. SQL/CQL adapters
--- and SurrealDB support this. The statement, selection, and buffer actions
--- each prompt once per distinct name, and cancelling any prompt leaves the
--- current result and staged edits untouched. Names are case-sensitive and
--- hold ASCII letters, digits, and underscores, starting with a letter or
--- underscore.
---
--- Most of the time you declare nothing: integers, finite decimals, and
--- true/false bind as native numbers and booleans, while anything else binds
--- as text. To force text, wrap the input as a JSON string such as `"42"`.
--- When a parameter needs a fixed type or default, declare it in a header
--- comment: >sql
---   -- @param user_id int = 42
---   -- @param status text = active
---   SELECT * FROM users WHERE id = :user_id AND status = :status;
--- <
--- The four types are `text`, `int` (signed 64-bit), `float` (finite), and
--- `bool` (`true`/`false`). Typing `NULL` binds a null of the declared type,
--- while empty text stays an empty string; for the literal word NULL as text,
--- enter the JSON string `"NULL"`. Values travel through the driver as bound
--- parameters, never pasted into the SQL. Placeholders cannot stand in for
--- table or column names, and they cannot mix with native positional
--- placeholders. Strings, quoted identifiers, comments, and PostgreSQL casts
--- are left alone. Inside PostgreSQL array subscripts, wrap the input in
--- parentheses as `items[(:index)]`, because a bare colon reads as a slice.
--- Selection and range runs read their declarations from the source buffer's
--- header.
---
--- From Lua you can answer prompts in code with raw input strings: >lua
---   require('sqmeow.api.query').execute(sql, { parameters = { user_id = '42' } })
--- <
--- An empty parameter map falls back to declared defaults, while missing
--- required values fail before anything runs. Refreshing a live result reuses
--- the values already in memory. Supplied values are not written to history,
--- though returned rows and edit-source metadata (including Redis keys) may be
--- archived. After a restart or result eviction, rerun from the scratchpad and
--- enter values again. Never put secrets in defaults; they are part of the
--- SQL text. A bare NULL binds a text null, so declare the type when the SQL
--- context needs a numeric or boolean null. Driver-specific value limits still
--- apply. Oracle treats empty strings as NULL, following its own semantics.
--- Oracle bound EXPLAIN and stored-program definitions are not supported yet;
--- plain bound SQL and anonymous PL/SQL blocks bind natively.
---
--- MongoDB commands take whole JSON string values rather than raw
--- substitution: >json
---   {"find":"users","filter":{"name":":name","age":{"$gte":":age"}}}
--- <
--- Values bind as BSON scalars. Command, database, collection, and field names
--- can never be parameters. Aggregation expression operands need `$literal`,
--- for example `{"$project":{"value":{"$literal":":value"}}}`. Executable
--- JavaScript and structural stage options cannot be parameters either. Bind
--- plain scalars, never fields tucked inside Extended JSON type wrappers.
--- Redis/Valkey/Dragonfly take whole unquoted arguments: >
---   HSET user:1 name :name
--- <
--- One supplied value always stays one Redis argument, even with spaces or
--- newlines inside. A quoted `':name'` stays literal text. Redis has no NULL
--- argument, so use empty text instead. Redis script bodies and subcommands
--- cannot be bound parameters. Neither adapter rewrites your query source.
---
--- Filtering and sorting ~
--- Filtering happens inside the plugin, not in the database. Press `gf` for a
--- WHERE bar and `go` for an ORDER BY bar above the grid. Type only the
--- expression, without the clause keyword, and press <CR> to apply it. For
--- shortcuts, `=` filters by the cell under the cursor, `s` cycles the
--- column's sort order, and `S` adds the column to a multi-column sort.
--- Every adapter shares the same Polars SQL dialect over the kept rows, so
--- this works for MongoDB and other NoSQL results, for disconnected
--- connections, and for restored history alike. The database query never
--- reruns, and staged edits survive filtering. Filtering sees every kept page
--- but cannot bring back rows the query itself left out or `max_rows` cut.
--- `R` clears filters, aggregation, sorting, and hidden columns, bringing back
--- the original snapshot. Rerun the query for fresh data; refreshing after
--- applying edits re-applies your local view on top of the new result.
---
--- The bar already prints the keywords, so type only the expressions: >
---   WHERE     age >= 18 AND status = 'active'
---   ORDER BY  age DESC NULLS LAST, id ASC
--- <
--- The dialect covers `AND`/`OR`/`NOT`, `IS NULL`, `LIKE`/`ILIKE`, `IN`, and
--- `BETWEEN`. Quote column names with double quotes and string values with
--- single quotes. Names are case-sensitive and must match the result; the
--- completion menu lists them. Repeated column names are numbered as `name`,
--- `name_2`, and so on. Full queries and subqueries are rejected; invalid
--- input simply keeps the previous view. `s` and `S` sort nulls last, while
--- ORDER BY expressions may say NULLS FIRST or NULLS LAST explicitly. Integers
--- and booleans are typed. Strings that look numeric still compare as strings,
--- so CAST Redis values for numeric work: CAST(value AS DOUBLE). Exact
--- decimals, temporal values, and nested JSON stay as text.
---
--- Snapshot aggregation ~
--- Press `gG` for GROUP BY in the same bar. List plain column names in GROUP
--- BY and built-in aggregates with explicit aliases in AGGREGATE: >
---   WHERE     active = 1
---   ORDER BY  total DESC
---   GROUP BY  country
---   AGGREGATE COUNT(*) AS users, SUM(amount) AS total
---   HAVING    users >= 10
--- <
--- Everything runs locally through Polars over the snapshot you already
--- queried, including kept or restored history after a disconnect. The
--- database query never reruns. GROUP BY accepts native Bool, Int, and Text
--- keys, and several keys at once. COUNT(*) counts rows while COUNT(column)
--- skips NULLs. SUM and AVG need native numeric columns; MIN and MAX accept
--- native numeric or text columns. An empty GROUP BY folds everything into one
--- global aggregate row. NULL keys form a single group, and an all-NULL
--- SUM/AVG/MIN/MAX yields NULL. Integer sums are overflow-checked and AVG
--- returns Float64. Mixed or special Object values and NaN/infinity are
--- rejected. WHERE filters before grouping; HAVING filters on the output
--- names after aggregation. Pressing `=` on an aggregate cell adds a HAVING
--- condition rather than touching the source WHERE. Groups keep their
--- first-seen order unless ORDER BY or grid sorting says otherwise. Aggregate
--- outputs get their own schema with paging, details, and export, but they are
--- read-only. Settle or discard staged edits before aggregating. A truncated
--- result aggregates only its kept rows. `R` brings back the original editable
--- snapshot. From Lua, call `require('sqmeow.api.view').aggregate({...})` with
--- the `group_by`, `aggregates`, `having`, `where`, and `order_by` strings.
--- Explicit casts can unlock numeric and temporal comparisons, though floats
--- may lose precision. Nested JSON fields are never flattened.
---
--- Editing ~
--- Edits are staged first and applied later, a little like git. Press `i` or
--- <CR> to stage a cell edit, `X` to stage NULL, and `dd` to stage deleting
--- the row. `u` undoes the last staged change; `U` discards every staged
--- change. `gs` or <C-s> opens a review of what will run; pressing <C-s> in
--- that review applies the changes to the database. Editing SQL results needs
--- direct table-column mappings plus the complete primary or unique key in the
--- result. Joined rows update each of their tables, while inserting rows works
--- only for single-table results. Read-only connections refuse edits, and
--- transaction guarantees depend on the database adapter.
---
--- Exporting ~
--- Press `x` for the export dialog, or select rows first and press visual `x`
--- to export just those. Formats are CSV, JSON, and SQL where the dialect
--- supports them. Exports use the kept result rows, never a fresh database
--- query, so a truncated result cannot export rows that were never fetched.
--- For a one-shot export without the dialog: >vim
---   Sqmeow export csv /tmp/result.csv
---   Sqmeow export json clipboard
--- <
--- Dialect differences ~
--- Redis expects one command per line. MongoDB expects Extended JSON commands.
--- ScyllaDB/Cassandra speak CQL and SurrealDB speaks SurrealQL. SQL Server
--- accepts standalone GO batch separators, but not GO repetition counts or
--- sqlcmd directives. `query.confirm_destructive` asks before destructive
--- statements; for guarantees the server itself must enforce, connect with a
--- read-only database account.
---@tag sqmeow-queries
---@toc_entry Query and result workflow

--- The query log ~
---
--- Every run is remembered in a query log. `:Sqmeow log` lists past runs and
--- reopens any result without executing its query again.
--- `query.history_size` caps how many runs the engine keeps in memory.
--- With `persist_history = true`, results are also archived to disk, so they
--- survive eviction and even a restart. `query.history_limit` caps how many
--- entries the log shows. `:Sqmeow log clear` deletes the saved log and its
--- archived results.
---
--- These files live under `core.path`, which defaults to
--- `stdpath('data') .. '/sqmeow'`:
---   bin/                 The installed engine binary.
---   connections.json     Your saved connection definitions.
---   scratch/             Scratchpad files; save them with `:write` like normal buffers.
---   history/log.jsonl    Query log metadata.
---   history/results/    Archived result data.
---   session.json        Open connection names and expanded drawer nodes.
---
--- With `ui.persist_session = true`, Neovim saves the session on exit and
--- reconnects the named connections the next time the drawer opens. Their
--- definitions must still exist in the configured sources. This restores
--- which connections were open, not live database sessions, temporary tables,
--- or in-memory databases. Project TOML stays in `.sqmeow/`; scratchpads and
--- history always live under `core.path`.
---@tag sqmeow-history
---@toc_entry The query log

--- Auto-completion ~
---
--- `blink.cmp` or `nvim-cmp` can complete schema, table, view, and column
--- names from the active connection as you type. Columns load on demand for
--- the relations in the current statement, including multiline SELECT, WHERE,
--- JOIN, GROUP BY, and ORDER BY. Table aliases and double-quoted, backtick,
--- and bracket-quoted identifiers all work, and you never need to open a
--- table in the drawer first. Smarter query-aware and alias completion needs
--- the `sql` Tree-sitter parser (derekstride/tree-sitter-sql); install it with
--- `:TSInstall sql` through nvim-treesitter. Without the parser, plain
--- metadata and `table.` column completion keep working.
---
--- To use with `blink.cmp`: >lua
---   require('blink.cmp').setup({
---     sources = {
---       default = { 'lsp', 'path', 'buffer', 'sqmeow' },
---       providers = {
---         sqmeow = {
---           name = 'Sqmeow',
---           module = 'sqmeow.completion.blink',
---         },
---       },
---     },
---   })
--- <
---
--- To use with `nvim-cmp`: >lua
---   require('cmp').setup({
---     sources = {
---       { name = 'sqmeow' },
---       -- ...
---     },
---   })
---   require('cmp').register_source('sqmeow', require('sqmeow.completion.cmp').new())
--- <
---@tag sqmeow-completion
---@toc_entry Auto-completion

--- Troubleshooting ~
---
--- Engine missing or outdated:
---   Run `:Sqmeow health` to see what is wrong, then `:Sqmeow install` to fix
---   it. On a master checkout, build with `:Sqmeow install cargo` and follow
---   with `:Sqmeow restart`.
--- Connection missing from the drawer:
---   Check `:pwd` for the working directory, the nearest project config, and
---   the `sources` order. The first entry wins on duplicate names. List source
---   errors with: >lua
---     local _, errors = require('sqmeow.api.connection').available()
---     vim.print(errors)
--- <
--- Query went to the wrong database:
---   Check `:Sqmeow bind` before `:Sqmeow use`. A buffer pin always wins over
---   the active connection.
--- Result cannot be edited:
---   The result must carry the table's full primary or unique key plus direct
---   table columns. Computed expressions and read-only connections never edit.
--- Completion lacks aliases or query context:
---   Install the SQL parser and open the target connection first; see
---   |sqmeow-completion|.
--- Need more diagnostics:
---   Set `core.log_level = 'debug'`, restart the engine, reproduce the
---   problem, then run `:Sqmeow messages`. Note that restarting drops all live
---   connections.
---@tag sqmeow-troubleshooting
---@toc_entry Troubleshooting

local M = {}

--- The configuration the user passed, kept unmerged for `:checkhealth`.
---@type table|nil
M.user_config = nil

--- Configure the plugin. Optional; partial tables override only named keys.
---@param opts table|nil See |sqmeow-config|.
---@usage >lua
---   require('sqmeow').setup({
---     ui = { drawer = { width = 40 } },
---   })
--- <
function M.setup(opts)
  M.user_config = opts or {}

  local _, errors = require('sqmeow.config').apply(M.user_config)
  for _, err in ipairs(errors) do
    require('sqmeow.core.utils').notify(err, vim.log.levels.ERROR)
  end

  require('sqmeow.ui.highlights').setup()

  -- A colourscheme change wipes every group, including ours.
  vim.api.nvim_create_autocmd('ColorScheme', {
    group = vim.api.nvim_create_augroup('sqmeow.highlights', { clear = true }),
    desc = 'Redefine sqmeow highlight groups',
    callback = function()
      require('sqmeow.ui.highlights').setup()
    end,
  })

  local session = vim.api.nvim_create_augroup('sqmeow.session', { clear = true })
  if require('sqmeow.config').get().ui.persist_session then
    vim.api.nvim_create_autocmd('VimLeavePre', {
      group = session,
      desc = 'Save the open sqmeow connections',
      callback = function()
        require('sqmeow.server.session').save()
      end,
    })
  end

  -- A running engine holds the old settings, so tell it about the new ones.
  require('sqmeow.rpc.client').configure()
end

--- Install the engine binary. Call it from a build hook, nothing else installs it: >lua
---   {
---     '2giosangmitom/sqmeow.nvim',
---     dependencies = { 'MunifTanjim/nui.nvim' },
---     build = function()
---       require('sqmeow').install()
---     end,
---     opts = {},
---   }
--- <
--- Without a method, downloads a release then falls back to cargo. Methods: `'cargo'`,
--- `'curl'`, `'wget'` and `'powershell'`: >lua
---   require('sqmeow').install('cargo')
---   require('sqmeow').install('wget')
---   require('sqmeow').install({ version = '1.0.2' })
--- <
--- Blocks until done unless a `callback` is given.
---@param opts string|table|nil A method name, or a table of `method`, `version`, `callback` and
---  `timeout` in milliseconds.
---@return boolean|nil ok Whether an engine was installed, or nil when a `callback` was given.
---@return string|nil err
function M.install(opts)
  return require('sqmeow.server.install').install(opts)
end

--- Stop the engine. It restarts on the next call that needs it.
function M.stop()
  require('sqmeow.rpc.client').stop()
end

return M
