INSERT INTO sqmeow_customers (id, name, email, city, active, note) VALUES (1, 'Alice Nguyen', 'customer01@example.test', 'Berlin', 1, 'literal :not_a_parameter');
INSERT INTO sqmeow_customers (id, name, email, city, active, note) VALUES (2, 'Bob O''Brien', 'customer02@example.test', 'São Paulo', 1, NULL);
INSERT INTO sqmeow_customers (id, name, email, city, active, note) VALUES (3, 'Carol Tran', 'customer03@example.test', 'Tokyo', 1, 'customer tier 0');
INSERT INTO sqmeow_customers (id, name, email, city, active, note) VALUES (4, 'Diego Silva', 'customer04@example.test', 'Hanoi', 1, 'customer tier 1');
INSERT INTO sqmeow_customers (id, name, email, city, active, note) VALUES (5, 'Emma Chen', 'customer05@example.test', 'Berlin', 0, NULL);
INSERT INTO sqmeow_customers (id, name, email, city, active, note) VALUES (6, 'Farah Ali', 'customer06@example.test', 'São Paulo', 1, 'customer tier 0');
INSERT INTO sqmeow_customers (id, name, email, city, active, note) VALUES (7, 'Grace Kim', 'customer07@example.test', 'Tokyo', 1, 'customer tier 1');
INSERT INTO sqmeow_customers (id, name, email, city, active, note) VALUES (8, 'Hugo Martin', 'customer08@example.test', 'Hanoi', 1, NULL);
INSERT INTO sqmeow_customers (id, name, email, city, active, note) VALUES (9, 'Iris Patel', 'customer09@example.test', 'Berlin', 1, 'customer tier 0');
INSERT INTO sqmeow_customers (id, name, email, city, active, note) VALUES (10, 'Jun Park', 'customer10@example.test', 'São Paulo', 0, 'customer tier 1');
INSERT INTO sqmeow_customers (id, name, email, city, active, note) VALUES (11, 'Kira Ivanov', 'customer11@example.test', 'Tokyo', 1, NULL);
INSERT INTO sqmeow_customers (id, name, email, city, active, note) VALUES (12, 'Liam Brown', 'customer12@example.test', 'Hanoi', 1, 'customer tier 0');
INSERT INTO sqmeow_customers (id, name, email, city, active, note) VALUES (13, 'Maya Singh', 'customer13@example.test', 'Berlin', 1, 'customer tier 1');
INSERT INTO sqmeow_customers (id, name, email, city, active, note) VALUES (14, 'Noah Wilson', 'customer14@example.test', 'São Paulo', 1, NULL);
INSERT INTO sqmeow_customers (id, name, email, city, active, note) VALUES (15, 'Olivia Garcia', 'customer15@example.test', 'Tokyo', 0, 'customer tier 0');
INSERT INTO sqmeow_customers (id, name, email, city, active, note) VALUES (16, 'Pavel Novak', 'customer16@example.test', 'Hanoi', 1, 'customer tier 1');
INSERT INTO sqmeow_customers (id, name, email, city, active, note) VALUES (17, 'Quinn Davis', 'customer17@example.test', 'Berlin', 1, NULL);
INSERT INTO sqmeow_customers (id, name, email, city, active, note) VALUES (18, 'Rosa Lopez', 'customer18@example.test', 'São Paulo', 1, 'customer tier 0');
INSERT INTO sqmeow_customers (id, name, email, city, active, note) VALUES (19, 'Sam Taylor', 'customer19@example.test', 'Tokyo', 1, 'customer tier 1');
INSERT INTO sqmeow_customers (id, name, email, city, active, note) VALUES (20, 'Tara Le', 'customer20@example.test', 'Hanoi', 0, NULL);

INSERT INTO sqmeow_products (id, sku, name, category, price_cents, stock_qty, note) VALUES (1, 'SMOKE-001', 'Books item 01', 'books', 675, 97, 'warehouse aisle 1');
INSERT INTO sqmeow_products (id, sku, name, category, price_cents, stock_qty, note) VALUES (2, 'SMOKE-002', 'Office item 02', 'office', 850, 94, 'warehouse aisle 2');
INSERT INTO sqmeow_products (id, sku, name, category, price_cents, stock_qty, note) VALUES (3, 'SMOKE-003', 'Audio item 03', 'audio', 1025, 91, 'warehouse aisle 3');
INSERT INTO sqmeow_products (id, sku, name, category, price_cents, stock_qty, note) VALUES (4, 'SMOKE-004', 'Hardware item 04', 'hardware', 1200, 88, NULL);
INSERT INTO sqmeow_products (id, sku, name, category, price_cents, stock_qty, note) VALUES (5, 'SMOKE-005', 'Books item 05', 'books', 1375, 85, 'warehouse aisle 0');
INSERT INTO sqmeow_products (id, sku, name, category, price_cents, stock_qty, note) VALUES (6, 'SMOKE-006', 'Office item 06', 'office', 1550, 82, 'warehouse aisle 1');
INSERT INTO sqmeow_products (id, sku, name, category, price_cents, stock_qty, note) VALUES (7, 'SMOKE-007', 'Audio item 07', 'audio', 1725, 79, 'warehouse aisle 2');
INSERT INTO sqmeow_products (id, sku, name, category, price_cents, stock_qty, note) VALUES (8, 'SMOKE-008', 'Hardware item 08', 'hardware', 1900, 76, NULL);
INSERT INTO sqmeow_products (id, sku, name, category, price_cents, stock_qty, note) VALUES (9, 'SMOKE-009', 'Books item 09', 'books', 2075, 73, 'warehouse aisle 4');
INSERT INTO sqmeow_products (id, sku, name, category, price_cents, stock_qty, note) VALUES (10, 'SMOKE-010', 'Office item 10', 'office', 2250, 70, 'warehouse aisle 0');
INSERT INTO sqmeow_products (id, sku, name, category, price_cents, stock_qty, note) VALUES (11, 'SMOKE-011', 'Audio item 11', 'audio', 2425, 67, 'warehouse aisle 1');
INSERT INTO sqmeow_products (id, sku, name, category, price_cents, stock_qty, note) VALUES (12, 'SMOKE-012', 'Hardware item 12', 'hardware', 2600, 64, NULL);
INSERT INTO sqmeow_products (id, sku, name, category, price_cents, stock_qty, note) VALUES (13, 'SMOKE-013', 'Books item 13', 'books', 2775, 61, 'warehouse aisle 3');
INSERT INTO sqmeow_products (id, sku, name, category, price_cents, stock_qty, note) VALUES (14, 'SMOKE-014', 'Office item 14', 'office', 2950, 58, 'warehouse aisle 4');
INSERT INTO sqmeow_products (id, sku, name, category, price_cents, stock_qty, note) VALUES (15, 'SMOKE-015', 'Audio item 15', 'audio', 3125, 55, 'warehouse aisle 0');
INSERT INTO sqmeow_products (id, sku, name, category, price_cents, stock_qty, note) VALUES (16, 'SMOKE-016', 'Hardware item 16', 'hardware', 3300, 52, NULL);
INSERT INTO sqmeow_products (id, sku, name, category, price_cents, stock_qty, note) VALUES (17, 'SMOKE-017', 'Books item 17', 'books', 3475, 49, 'warehouse aisle 2');
INSERT INTO sqmeow_products (id, sku, name, category, price_cents, stock_qty, note) VALUES (18, 'SMOKE-018', 'Office item 18', 'office', 3650, 46, 'warehouse aisle 3');
INSERT INTO sqmeow_products (id, sku, name, category, price_cents, stock_qty, note) VALUES (19, 'SMOKE-019', 'Audio item 19', 'audio', 3825, 43, 'warehouse aisle 4');
INSERT INTO sqmeow_products (id, sku, name, category, price_cents, stock_qty, note) VALUES (20, 'SMOKE-020', 'Hardware item 20', 'hardware', 4000, 40, NULL);

INSERT INTO sqmeow_orders (id, customer_id, ordered_on, status, total_cents, note) VALUES (1, 1, DATE '2026-09-01', 'paid', 3450, 'delivery window 1');
INSERT INTO sqmeow_orders (id, customer_id, ordered_on, status, total_cents, note) VALUES (2, 2, DATE '2026-09-02', 'shipped', 8850, NULL);
INSERT INTO sqmeow_orders (id, customer_id, ordered_on, status, total_cents, note) VALUES (3, 3, DATE '2026-09-03', 'cancelled', 2600, 'delivery window 0');
INSERT INTO sqmeow_orders (id, customer_id, ordered_on, status, total_cents, note) VALUES (4, 4, DATE '2026-09-04', 'new', 1900, NULL);
INSERT INTO sqmeow_orders (id, customer_id, ordered_on, status, total_cents, note) VALUES (5, 5, DATE '2026-09-05', 'paid', 6250, 'delivery window 2');
INSERT INTO sqmeow_orders (id, customer_id, ordered_on, status, total_cents, note) VALUES (6, 6, DATE '2026-09-06', 'shipped', 2450, NULL);
INSERT INTO sqmeow_orders (id, customer_id, ordered_on, status, total_cents, note) VALUES (7, 7, DATE '2026-09-07', 'cancelled', 8300, 'delivery window 1');
INSERT INTO sqmeow_orders (id, customer_id, ordered_on, status, total_cents, note) VALUES (8, 8, DATE '2026-09-08', 'new', 3300, NULL);
INSERT INTO sqmeow_orders (id, customer_id, ordered_on, status, total_cents, note) VALUES (9, 9, DATE '2026-09-09', 'paid', 1950, 'delivery window 0');
INSERT INTO sqmeow_orders (id, customer_id, ordered_on, status, total_cents, note) VALUES (10, 10, DATE '2026-09-10', 'shipped', 6750, NULL);
INSERT INTO sqmeow_orders (id, customer_id, ordered_on, status, total_cents, note) VALUES (11, 11, DATE '2026-09-11', 'cancelled', 13900, 'delivery window 2');
INSERT INTO sqmeow_orders (id, customer_id, ordered_on, status, total_cents, note) VALUES (12, 12, DATE '2026-09-12', 'new', 1100, NULL);
INSERT INTO sqmeow_orders (id, customer_id, ordered_on, status, total_cents, note) VALUES (13, 1, DATE '2026-09-13', 'paid', 4850, 'delivery window 1');
INSERT INTO sqmeow_orders (id, customer_id, ordered_on, status, total_cents, note) VALUES (14, 2, DATE '2026-09-14', 'shipped', 10950, NULL);
INSERT INTO sqmeow_orders (id, customer_id, ordered_on, status, total_cents, note) VALUES (15, 3, DATE '2026-09-15', 'cancelled', 5400, 'delivery window 0');
INSERT INTO sqmeow_orders (id, customer_id, ordered_on, status, total_cents, note) VALUES (16, 4, DATE '2026-09-16', 'new', 2600, NULL);
INSERT INTO sqmeow_orders (id, customer_id, ordered_on, status, total_cents, note) VALUES (17, 5, DATE '2026-09-17', 'paid', 7650, 'delivery window 2');
INSERT INTO sqmeow_orders (id, customer_id, ordered_on, status, total_cents, note) VALUES (18, 6, DATE '2026-09-18', 'shipped', 4550, NULL);
INSERT INTO sqmeow_orders (id, customer_id, ordered_on, status, total_cents, note) VALUES (19, 7, DATE '2026-09-19', 'cancelled', 11100, 'delivery window 1');
INSERT INTO sqmeow_orders (id, customer_id, ordered_on, status, total_cents, note) VALUES (20, 8, DATE '2026-09-20', 'new', 4000, NULL);

INSERT INTO sqmeow_order_items (id, order_id, product_id, quantity, unit_price_cents, discount_cents) VALUES (1, 1, 7, 2, 1725, 0);
INSERT INTO sqmeow_order_items (id, order_id, product_id, quantity, unit_price_cents, discount_cents) VALUES (2, 2, 14, 3, 2950, 0);
INSERT INTO sqmeow_order_items (id, order_id, product_id, quantity, unit_price_cents, discount_cents) VALUES (3, 3, 1, 4, 675, 100);
INSERT INTO sqmeow_order_items (id, order_id, product_id, quantity, unit_price_cents, discount_cents) VALUES (4, 4, 8, 1, 1900, 0);
INSERT INTO sqmeow_order_items (id, order_id, product_id, quantity, unit_price_cents, discount_cents) VALUES (5, 5, 15, 2, 3125, 0);
INSERT INTO sqmeow_order_items (id, order_id, product_id, quantity, unit_price_cents, discount_cents) VALUES (6, 6, 2, 3, 850, 100);
INSERT INTO sqmeow_order_items (id, order_id, product_id, quantity, unit_price_cents, discount_cents) VALUES (7, 7, 9, 4, 2075, 0);
INSERT INTO sqmeow_order_items (id, order_id, product_id, quantity, unit_price_cents, discount_cents) VALUES (8, 8, 16, 1, 3300, 0);
INSERT INTO sqmeow_order_items (id, order_id, product_id, quantity, unit_price_cents, discount_cents) VALUES (9, 9, 3, 2, 1025, 100);
INSERT INTO sqmeow_order_items (id, order_id, product_id, quantity, unit_price_cents, discount_cents) VALUES (10, 10, 10, 3, 2250, 0);
INSERT INTO sqmeow_order_items (id, order_id, product_id, quantity, unit_price_cents, discount_cents) VALUES (11, 11, 17, 4, 3475, 0);
INSERT INTO sqmeow_order_items (id, order_id, product_id, quantity, unit_price_cents, discount_cents) VALUES (12, 12, 4, 1, 1200, 100);
INSERT INTO sqmeow_order_items (id, order_id, product_id, quantity, unit_price_cents, discount_cents) VALUES (13, 13, 11, 2, 2425, 0);
INSERT INTO sqmeow_order_items (id, order_id, product_id, quantity, unit_price_cents, discount_cents) VALUES (14, 14, 18, 3, 3650, 0);
INSERT INTO sqmeow_order_items (id, order_id, product_id, quantity, unit_price_cents, discount_cents) VALUES (15, 15, 5, 4, 1375, 100);
INSERT INTO sqmeow_order_items (id, order_id, product_id, quantity, unit_price_cents, discount_cents) VALUES (16, 16, 12, 1, 2600, 0);
INSERT INTO sqmeow_order_items (id, order_id, product_id, quantity, unit_price_cents, discount_cents) VALUES (17, 17, 19, 2, 3825, 0);
INSERT INTO sqmeow_order_items (id, order_id, product_id, quantity, unit_price_cents, discount_cents) VALUES (18, 18, 6, 3, 1550, 100);
INSERT INTO sqmeow_order_items (id, order_id, product_id, quantity, unit_price_cents, discount_cents) VALUES (19, 19, 13, 4, 2775, 0);
INSERT INTO sqmeow_order_items (id, order_id, product_id, quantity, unit_price_cents, discount_cents) VALUES (20, 20, 20, 1, 4000, 0);

INSERT INTO sqmeow_payments (id, order_id, paid_on, method, amount_cents, status, note) VALUES (1, 1, DATE '2026-09-01', 'bank', 3450, 'settled', 'receipt 001');
INSERT INTO sqmeow_payments (id, order_id, paid_on, method, amount_cents, status, note) VALUES (2, 2, DATE '2026-09-02', 'cash', 8850, 'settled', 'receipt 002');
INSERT INTO sqmeow_payments (id, order_id, paid_on, method, amount_cents, status, note) VALUES (3, 3, DATE '2026-09-03', 'card', 2600, 'settled', NULL);
INSERT INTO sqmeow_payments (id, order_id, paid_on, method, amount_cents, status, note) VALUES (4, 4, DATE '2026-09-04', 'bank', 1900, 'pending', 'receipt 004');
INSERT INTO sqmeow_payments (id, order_id, paid_on, method, amount_cents, status, note) VALUES (5, 5, DATE '2026-09-05', 'cash', 6250, 'settled', 'receipt 005');
INSERT INTO sqmeow_payments (id, order_id, paid_on, method, amount_cents, status, note) VALUES (6, 6, DATE '2026-09-06', 'card', 2450, 'settled', NULL);
INSERT INTO sqmeow_payments (id, order_id, paid_on, method, amount_cents, status, note) VALUES (7, 7, DATE '2026-09-07', 'bank', 8300, 'settled', 'receipt 007');
INSERT INTO sqmeow_payments (id, order_id, paid_on, method, amount_cents, status, note) VALUES (8, 8, DATE '2026-09-08', 'cash', 3300, 'pending', 'receipt 008');
INSERT INTO sqmeow_payments (id, order_id, paid_on, method, amount_cents, status, note) VALUES (9, 9, DATE '2026-09-09', 'card', 1950, 'settled', NULL);
INSERT INTO sqmeow_payments (id, order_id, paid_on, method, amount_cents, status, note) VALUES (10, 10, DATE '2026-09-10', 'bank', 6750, 'settled', 'receipt 010');
INSERT INTO sqmeow_payments (id, order_id, paid_on, method, amount_cents, status, note) VALUES (11, 11, DATE '2026-09-11', 'cash', 13900, 'settled', 'receipt 011');
INSERT INTO sqmeow_payments (id, order_id, paid_on, method, amount_cents, status, note) VALUES (12, 12, DATE '2026-09-12', 'card', 1100, 'pending', NULL);
INSERT INTO sqmeow_payments (id, order_id, paid_on, method, amount_cents, status, note) VALUES (13, 13, DATE '2026-09-13', 'bank', 4850, 'settled', 'receipt 013');
INSERT INTO sqmeow_payments (id, order_id, paid_on, method, amount_cents, status, note) VALUES (14, 14, DATE '2026-09-14', 'cash', 10950, 'settled', 'receipt 014');
INSERT INTO sqmeow_payments (id, order_id, paid_on, method, amount_cents, status, note) VALUES (15, 15, DATE '2026-09-15', 'card', 5400, 'settled', NULL);
INSERT INTO sqmeow_payments (id, order_id, paid_on, method, amount_cents, status, note) VALUES (16, 16, DATE '2026-09-16', 'bank', 2600, 'pending', 'receipt 016');
INSERT INTO sqmeow_payments (id, order_id, paid_on, method, amount_cents, status, note) VALUES (17, 17, DATE '2026-09-17', 'cash', 7650, 'settled', 'receipt 017');
INSERT INTO sqmeow_payments (id, order_id, paid_on, method, amount_cents, status, note) VALUES (18, 18, DATE '2026-09-18', 'card', 4550, 'settled', NULL);
INSERT INTO sqmeow_payments (id, order_id, paid_on, method, amount_cents, status, note) VALUES (19, 19, DATE '2026-09-19', 'bank', 11100, 'settled', 'receipt 019');
INSERT INTO sqmeow_payments (id, order_id, paid_on, method, amount_cents, status, note) VALUES (20, 20, DATE '2026-09-20', 'cash', 4000, 'pending', 'receipt 020');
